//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/InputPlayer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayer: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayer"",
    ""maps"": [
        {
            ""name"": ""PlayerControllerMap"",
            ""id"": ""3a5c90cc-794b-4184-bb24-21bddb7e05f2"",
            ""actions"": [
                {
                    ""name"": ""Agrresif"",
                    ""type"": ""Button"",
                    ""id"": ""3bee58fa-fb54-4949-9d9d-994913132bb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0e6472ee-c537-48d8-9ed4-eca3333a049c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Agrresif"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControllerMap
        m_PlayerControllerMap = asset.FindActionMap("PlayerControllerMap", throwIfNotFound: true);
        m_PlayerControllerMap_Agrresif = m_PlayerControllerMap.FindAction("Agrresif", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControllerMap
    private readonly InputActionMap m_PlayerControllerMap;
    private List<IPlayerControllerMapActions> m_PlayerControllerMapActionsCallbackInterfaces = new List<IPlayerControllerMapActions>();
    private readonly InputAction m_PlayerControllerMap_Agrresif;
    public struct PlayerControllerMapActions
    {
        private @InputPlayer m_Wrapper;
        public PlayerControllerMapActions(@InputPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Agrresif => m_Wrapper.m_PlayerControllerMap_Agrresif;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControllerMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllerMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerControllerMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerControllerMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerControllerMapActionsCallbackInterfaces.Add(instance);
            @Agrresif.started += instance.OnAgrresif;
            @Agrresif.performed += instance.OnAgrresif;
            @Agrresif.canceled += instance.OnAgrresif;
        }

        private void UnregisterCallbacks(IPlayerControllerMapActions instance)
        {
            @Agrresif.started -= instance.OnAgrresif;
            @Agrresif.performed -= instance.OnAgrresif;
            @Agrresif.canceled -= instance.OnAgrresif;
        }

        public void RemoveCallbacks(IPlayerControllerMapActions instance)
        {
            if (m_Wrapper.m_PlayerControllerMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerControllerMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerControllerMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerControllerMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerControllerMapActions @PlayerControllerMap => new PlayerControllerMapActions(this);
    public interface IPlayerControllerMapActions
    {
        void OnAgrresif(InputAction.CallbackContext context);
    }
}
